version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --immutable
            - run: yarn build
            - run: yarn test
            - run:
                name: Firebase Deploy
                command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
workflows:
    build-and-test:
      jobs:
        - build-and-test